name: spoyify_env
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - blas=1.0
  - matplotlib=3.2.1
  - openblas=0.3.9
  - pip=20.0.2
  - python=3.7.7
  - requests=2.23.0
  - scipy=1.4.1
  - seaborn=0.10.1
  - selenium=3.141.0
